name: 'Vulnerability Scan'
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Scan for vulnerabilities
        uses: anchore/scan-action@v3
        with:
          path: "."
          output-format: "table"